### ISSUE TITLE
Segmentation Fault after receiving sensor inputs

### ISSUE THREAD

**Issue by Megacephalo** [tstoyanov/perception_oru-release#6]
Hi there !
I am recently studying ways of find methods regarding localization in highly dynamic environments and was extremely happy to come across this project. Thank you for your effort of implementing such great idea and offering it to the public.
However, when I tried to run NDT_Fuser following the [tutorial](http://wiki.ros.org/perception_oru/Tutorials/Using%20NDT%20Fuser%20to%20create%20an%20NDT%20map) you had posted, the ndt_fuser_node crashes every time when it receives messages from the mapping.bag file. The terminal throws error message such as:
```
[laser_fuser_2d-2] process has died [pid 15985, exit code -11
```
I tried looking further into the issue and found out that it is actually a Segmentation Fault that terminates the thread. I am not sure whether it is a memory leak or anything else, but the problem seems to come from `lslgeneric::toMessage(NDTMap *map, ndt_map::NDTMapMsg &msg,std::string frame_name)` function in publish_map() and by what I'd seen, all pointers are properly initialized and deleted. So what could have been the true cause? 
If you are not available to look into it, would you kindly give me some clues I am happy to help out! Thank you for your patience and kindness.

**Comment by tstoyanov** [comment]
Hi,
we are preparing a new release at the moment and a public push of the current private source repository. Maybe it makes sense to wait for a couple of weeks and try to replicate the bug with the new release? By the way, what ros version are you running? 

Help is always welcome of course, so I will get back to you when I try to replicate the bug.

**Comment by Megacephalo** [comment]
Hi Todor,
I am amazed at your quick response! I wish that the new release wouldn't run into the same error. 
My environment is as follows:
Linux Ubuntu 14.04
ROS Indigo
perception-release-oru branch: debian/indigo/ndt_fuser & debian/indigo/ndt_map
And the rest are installed with Debian.

I will surely be trying for your new releases. Thank you so much !

**Comment by Megacephalo** [comment]
Hi Todor again !
There is something interesting to let you know.  I removed all ndt_* packages and related binary files which were built from source. I then Installed every single one of these packages again from Debian. This time GDB shows the frames stack as listed below. I found out that since my computer is running on NVIDIA binary driver version 367.57, it somewhat provokes conflict or maybe it crashes when NDTViz (the window does appear at first) is about to draw anything on the screen. This crash causes NDTViz window to close, throws Segmentation Fault and subsequently shuts down the thread altogether.  This problem is also reported by my colleague who also runs on NVIDIA driver.
I bypassed this problem by setting `<param name="visualize" value="true" />` to false, so that I can successfully save the map.

The frame stack report is as follows:
```
#0  0x00007ffff574bdc9 in glLoadIdentity () from /usr/lib/nvidia-367/libGL.so.1

#1  0x00007ffff735ba7d in NDTVizGlut::update_cam() () from /opt/ros/indigo/lib/libndt_visualisation.so

#2  0x00007ffff735c0c1 in NDTVizGlut::setCameraPointingToPoint(double, double, double) () from /opt/ros/indigo/lib/libndt_visualisation.so

#3  0x00007ffff7bc8a61 in lslgeneric::NDTFuserHMT::initialize(Eigen::Transform<double, 3, 2, 0>, pcl::PointCloud<pcl::PointXYZ>&, bool) () from /opt/ros/indigo/lib/libndt_fuser.so

#4  0x000000000044f3a7 in NDTFuserNode::processFrame(pcl::PointCloud<pcl::PointXYZ>&, Eigen::Transform<double, 3, 2, 0>) ()

#5  0x0000000000455473 in NDTFuserNode::laserOdomCallback(boost::shared_ptr<sensor_msgs::LaserScan_<std::allocator<void> > const> const&, boost::shared_ptr<nav_msgs::Odometry_<std::allocator<void> > const> const&) ()

#6  0x00000000004427f2 in boost::detail::function::void_function_obj_invoker9<boost::function<void (boost::shared_ptr<sensor_msgs::LaserScan_<std::allocator<void> > const> const&, boost::shared_ptr<nav_msgs::Odometry_<std::allocator<void> > const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&)>, void, boost::shared_ptr<sensor_msgs::LaserScan_<std::allocator<void> > const>, boost::shared_ptr<nav_msgs::Odometry_<std::allocator<void> > const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const> >::invoke(boost::detail::function::function_buffer&, boost::shared_ptr<sensor_msgs::LaserScan_<std::allocator<void> > const>, boost::shared_ptr<nav_msgs::Odometry_<std::allocator<void> > const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>) ()

#7  0x0000000000477f8e in boost::function9<void, boost::shared_ptr<sensor_msgs::LaserScan_<std::allocator<void> > const>, boost::shared_ptr<nav_msgs::Odometry_<std::allocator<void> > const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const> >::operator()(boost::shared_ptr<sensor_msgs::LaserScan_<std::allocator<void> > const>, boost::shared_ptr<nav_msgs::Odometry_<std::allocator<void> > const>, boost::sha---Type <return> to continue, or q <return> to quit---r
red_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>, boost::shared_ptr<message_filters::NullType const>) const ()

#8  0x0000000000478487 in message_filters::CallbackHelper9T<boost::shared_ptr<sensor_msgs::LaserScan_<std::allocator<void> > const> const&, boost::shared_ptr<nav_msgs::Odometry_<std::allocator<void> > const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&>::call(bool, ros::MessageEvent<sensor_msgs::LaserScan_<std::allocator<void> > const> const&, ros::MessageEvent<nav_msgs::Odometry_<std::allocator<void> > const> const&, ros::MessageEvent<message_filters::NullType const> const&, ros::MessageEvent<message_filters::NullType const> const&, ros::MessageEvent<message_filters::NullType const> const&, ros::MessageEvent<message_filters::NullType const> const&, ros::MessageEvent<message_filters::NullType const> const&, ros::MessageEvent<message_filters::NullType const> const&, ros::MessageEvent<message_filters::NullType const> const&) ()

#9  0x0000000000470a5f in message_filters::sync_policies::ApproximateTime<sensor_msgs::LaserScan_<std::allocator<void> >, nav_msgs::Odometry_<std::allocator<void> >, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType>::publishCandidate() ()

#10 0x00000000004741f8 in message_filters::sync_policies::ApproximateTime<sensor_msgs::LaserScan_<std::allocator<void> >, nav_msgs::Odometry_<std::allocator<void> >, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType>::process() ()

#11 0x0000000000475824 in void message_filters::sync_policies::ApproximateTime<sensor_msgs::LaserScan_<std::allocator<void> >, nav_msgs::Odometry_<std::allocator<void> >, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType>::add<1>(boost::mpl::at_c<boost::mpl::vector<ros::MessageEvent<sensor_msgs::LaserScan_<std::allocator<void> > const>, ros::MessageEvent<nav_msgs::Odometry_<std::allocator<void> > const>, ros::MessageEvent<message_filters::NullType const>, ros::MessageEvent<message_filters::NullType const>, ros::MessageEvent<message_filters::NullType const>, ros::MessageEvent<message_filters::NullType const>, ros::MessageEvent<message_filters::NullType const>, ros::MessageEvent<message_filters::NullType const>, ros::MessageEvent<message_filters::NullType const>, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, ---Type <return> to continue, or q <return> to quit---r
mpl_::na, mpl_::na, mpl_::na>, 1>::type const&) ()

#12 0x00000000004585fd in message_filters::CallbackHelper1T<ros::MessageEvent<nav_msgs::Odometry_<std::allocator<void> > const> const&, nav_msgs::Odometry_<std::allocator<void> > >::call(ros::MessageEvent<nav_msgs::Odometry_<std::allocator<void> > const> const&, bool)
    ()

#13 0x0000000000440f97 in message_filters::Subscriber<nav_msgs::Odometry_<std::allocator<void> > >::cb(ros::MessageEvent<nav_msgs::Odometry_<std::allocator<void> > const> const&)
    ()

#14 0x000000000047972f in ros::SubscriptionCallbackHelperT<ros::MessageEvent<nav_msgs::Odometry_<std::allocator<void> > const> const&, void>::call(ros::SubscriptionCallbackHelperCallParams&) ()

#15 0x00007ffff678f6b5 in ros::SubscriptionQueue::call() ()
   from /opt/ros/indigo/lib/libroscpp.so

#16 0x00007ffff6749107 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) ()
   from /opt/ros/indigo/lib/libroscpp.so



#17 0x00007ffff6749c33 in ros::CallbackQueue::callAvailable(ros::WallDuration) ()
   from /opt/ros/indigo/lib/libroscpp.so

#18 0x00007ffff67921e5 in ros::SingleThreadedSpinner::spin(ros::CallbackQueue*) ()
   from /opt/ros/indigo/lib/libroscpp.so

#19 0x00007ffff6779e0b in ros::spin() () from /opt/ros/indigo/lib/libroscpp.so

#20 0x00000000004366ed in main ()
```

**Comment by tstoyanov** [comment]
Hi,

thanks for pointing out this issue and for diagnosing it! I could replicate the problem on my machine in our develop branch, running the same version of the nvidia drivers as you. On a second machine with a different graphics card and an nvidia340 binary driver the issue does not occur.

For the moment my suggestion is to try either downgrading the nvidia driver, or installing a newer version from the nvidia website.

Let me know if any of these options reolve the problem.
